#!/usr/bin/env php
<?php
/**
 * CLI entry point. Run from the public directory:
 *   php cli <command>
 *   php cli migrate
 *   php cli help
 */
if (php_sapi_name() !== 'cli') {
    fwrite(STDERR, "This script can only be run from the command line.\n");
    exit(1);
}
require __DIR__ . DIRECTORY_SEPARATOR . 'commands' . DIRECTORY_SEPARATOR . 'cli.php';
